# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c24199172675309813472f3aef34ededab5ae39faf96ca029e3f63912027862481b7dfcd838a7a2f8cc1d594374a654f4402b73c696a9decd771ba521fdf044a

test:
  secret_key_base: c0d47c8a2a0658b00d765132705080faaafa7a1e37182fb29167f017e44be54da1b628410ab21d48eb9d52d6650822f9232e0bf574e29c24284dd3e0cce45e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
