# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae0f94717004a8565eb57e59a46cfc7a2e5894d6f03af2cf547f632685ec4f01af407c9e1fc43a2a3132562b4fb1a456aceb2d91673e87056f469c23fa1ada9

test:
  secret_key_base: 56303e9a45b95fa9b6fd9a0ae2165a4f21d0719d110577c486aa7e53f133742a96dc7abf37ffdea7d818e81c91937deefce62a10c780711000b1d2a035cc0eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
