# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5b7f61e370c28a0c1326ecd77dce147b37aa6e40d8846410c4559104da75c14789b9d6fdf9094bcfcd0e6212a0a68d55c4b0fccdf094332f27e01461813e3c

test:
  secret_key_base: 4379791b81f55b0ee9dc5276b5bb03f902215d9658efbf412e60852d3323a02b7805999e2ba1925e8b4fc66206e815efe576f7d9c35c09e6f1579cbf24cfd83f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
